#!/bin/bash

echo "==================================="
echo "GitHub Repository Setup for YappText"
echo "==================================="
echo ""
echo "Since GitHub CLI is not installed, please follow these steps:"
echo ""
echo "1. Go to: https://github.com/new"
echo ""
echo "2. Create a new repository with these settings:"
echo "   - Repository name: yapptext"
echo "   - Description: Simple audio transcription app using OpenAI Whisper"
echo "   - Public repository: ✓"
echo "   - Initialize repository: DO NOT check any boxes (no README, .gitignore, or license)"
echo ""
echo "3. After creating, GitHub will show you commands. Use these:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/yapptext.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "Replace YOUR_USERNAME with your GitHub username."
echo ""
echo "==================================="
echo "Alternative: Install GitHub CLI"
echo "==================================="
echo ""
echo "To install GitHub CLI for future use:"
echo "brew install gh"
echo ""
echo "Then authenticate:"
echo "gh auth login"
echo ""
echo "Then create repo:"
echo "gh repo create yapptext --public --source=. --remote=origin --push"
echo ""